# Generated by Django 3.2.9 on 2022-02-12 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ваш район')),
                ('slug', models.SlugField(verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('slug', models.SlugField(max_length=255, verbose_name='Url')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуем загружать реальные фото', null=True, upload_to='images/executors/', verbose_name='Ваше фото')),
                ('text', models.TextField(max_length=500, null=True, verbose_name='Расскажите о себе')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('time_work', models.CharField(max_length=255, null=True, verbose_name='Рабочее время')),
                ('days_of_work', models.CharField(max_length=255, null=True, verbose_name='Дни работы')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование')),
                ('certificates', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Мои сертификаты')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='needs.category', verbose_name='Выберите категорию для деятельности')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='needs.district', verbose_name='Район(ы) выполнение заказов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исполитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='MyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Примеры моих работ')),
                ('description', models.TextField(max_length=255, verbose_name='Описание выполненых работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/complete_orders/', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Выполненый заказ',
                'verbose_name_plural': 'Выполненые заказы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='заказ')),
                ('slug', models.SlugField(unique_for_date='publish', verbose_name='Url')),
                ('publish', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('description', models.TextField(max_length=255, verbose_name='описание')),
                ('image', models.ImageField(null=True, upload_to='images/orders/', verbose_name='Изображения')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='Ориентировочная цена')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Адресс заказа')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='needs.category', verbose_name='Категория товара')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='needs.district', verbose_name='Район заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-publish', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderAgainPublishView',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='needs.order')),
            ],
            bases=(django.views.generic.base.View, 'needs.order'),
        ),
        migrations.CreateModel(
            name='OrderRemovePublishView',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='needs.order')),
            ],
            bases=(django.views.generic.base.View, 'needs.order'),
        ),
        migrations.CreateModel(
            name='ResponseForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Текст отклика')),
                ('time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время отклика')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='needs.order', verbose_name='Заказ для отклика')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='needs.executor', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Отклик для заказа',
                'verbose_name_plural': 'Отклики для заказа',
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('slug', models.SlugField(max_length=255, verbose_name='Url')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('photo', models.ImageField(help_text='Размер фото не должен превышать 50кБайт', null=True, upload_to='images/requesters/', verbose_name='Ваше фото')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказщик',
                'verbose_name_plural': 'Заказщики',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.requester', verbose_name='заказщик'),
        ),
        migrations.AddField(
            model_name='executor',
            name='works',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.myorders', verbose_name='Мои работы'),
        ),
    ]
