# Generated by Django 3.2.9 on 2022-02-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_alter_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='works',
        ),
        migrations.AddField(
            model_name='myorders',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='needs.executor', verbose_name='Исполнитель'),
        ),
    ]
